export const get_example = () => {
  return {
    criterias: [
      'Chills',
      'Nasal congestion',
      'Headache',
      'Cough',
      'Sore throat',
      'Sputum production',
      'Fatigue',
      'Shortness of breath',
      'Fever',
    ],
    alternates: ['H1N1', 'COVID-19', 'H5N1', 'Hanta Virus', 'SARS'],
    criterias_config: {
      values: {
        Chills: { beneficial: true, compared2best: 5, compared2worst: 4 },
        'Nasal congestion': {
          beneficial: true,
          compared2best: 7,
          compared2worst: 3,
        },
        Headache: { beneficial: true, compared2best: 4, compared2worst: 6 },
        Cough: { beneficial: true, compared2best: 1, compared2worst: 9 },
        'Sore throat': {
          beneficial: true,
          compared2best: 3,
          compared2worst: 7,
        },
        'Sputum production': {
          beneficial: false,
          compared2best: 8,
          compared2worst: 2,
        },
        Fatigue: { beneficial: true, compared2best: 6, compared2worst: 5 },
        'Shortness of breath': {
          beneficial: false,
          compared2best: 9,
          compared2worst: 1,
        },
        Fever: { beneficial: true, compared2best: 2, compared2worst: 8 },
      },
      best_criteria: 'Cough',
      worst_criteria: 'Shortness of breath',
    },
    decisions: [
      {
        H1N1: {
          Chills: {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Nasal congestion': {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          Headache: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Cough: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Sore throat': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fatigue: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Shortness of breath': {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          Fever: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
        },
        'COVID-19': {
          Chills: {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Nasal congestion': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Headache: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Cough: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Sore throat': {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.45,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Fatigue: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Shortness of breath': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Fever: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
        },
        H5N1: {
          Chills: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Nasal congestion': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Headache: {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          Cough: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Sore throat': {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Fatigue: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Shortness of breath': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fever: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
        },
        'Hanta Virus': {
          Chills: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Nasal congestion': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Headache: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Cough: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Sore throat': {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Sputum production': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fatigue: {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Shortness of breath': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fever: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
        },
        SARS: {
          Chills: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Nasal congestion': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Headache: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          Cough: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Sore throat': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Fatigue: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Shortness of breath': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fever: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
        },
      },
      {
        H1N1: {
          Chills: {
            low: 0.45,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          'Nasal congestion': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Headache: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          Cough: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Sore throat': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fatigue: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Shortness of breath': {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          Fever: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
        },
        'COVID-19': {
          Chills: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Nasal congestion': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Headache: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          Cough: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Sore throat': {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          Fatigue: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Shortness of breath': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Fever: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
        },
        H5N1: {
          Chills: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Nasal congestion': {
            low: 0.1,
            mid: 0.25,
            high: 0.3,
            T: 0.1,
            I: 0.3,
            F: 0.1,
          },
          Headache: {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          Cough: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Sore throat': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Fatigue: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Shortness of breath': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fever: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
        },
        'Hanta Virus': {
          Chills: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Nasal congestion': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Headache: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Cough: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Sore throat': {
            low: 0.45,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fatigue: {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Shortness of breath': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fever: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
        },
        SARS: {
          Chills: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Nasal congestion': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Headache: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          Cough: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Sore throat': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Fatigue: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Shortness of breath': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fever: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
        },
      },
      {
        H1N1: {
          Chills: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Nasal congestion': {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          Headache: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          Cough: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Sore throat': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fatigue: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Shortness of breath': {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          Fever: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
        },
        'COVID-19': {
          Chills: {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Nasal congestion': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Headache: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Cough: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Sore throat': {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.45,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Fatigue: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Shortness of breath': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Fever: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
        },
        H5N1: {
          Chills: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Nasal congestion': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Headache: {
            low: 0.45,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Cough: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Sore throat': {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.1,
            mid: 0.25,
            high: 0.3,
            T: 0.1,
            I: 0.3,
            F: 0.1,
          },
          Fatigue: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Shortness of breath': {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          Fever: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
        },
        'Hanta Virus': {
          Chills: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Nasal congestion': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Headache: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          Cough: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Sore throat': {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Sputum production': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fatigue: {
            low: 0.5,
            mid: 0.5,
            high: 0.5,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Shortness of breath': {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          Fever: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
        },
        SARS: {
          Chills: {
            low: 0.85,
            mid: 0.8,
            high: 0.95,
            T: 0.8,
            I: 0.1,
            F: 0.2,
          },
          'Nasal congestion': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Headache: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          Cough: {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          'Sore throat': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          'Sputum production': {
            low: 0.2,
            mid: 0.3,
            high: 0.5,
            T: 0.6,
            I: 0.1,
            F: 0.2,
          },
          Fatigue: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
          'Shortness of breath': {
            low: 0.7,
            mid: 0.75,
            high: 0.8,
            T: 0.9,
            I: 0.2,
            F: 0.2,
          },
          Fever: {
            low: 0.95,
            mid: 0.9,
            high: 0.95,
            T: 0.9,
            I: 0.1,
            F: 0.1,
          },
        },
      },
    ],
  };
};
